# Generated by Django 2.1.2 on 2018-10-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_device_last_packet'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp_start', models.DateTimeField(db_index=True)),
                ('timestamp_end', models.DateTimeField(db_index=True)),
                ('packets_count', models.BigIntegerField(default=0)),
                ('packets_size', models.BigIntegerField(default=0)),
                ('dst_ips', models.TextField(blank=True, null=True)),
                ('dns_queries', models.TextField(blank=True, null=True)),
                ('http_hosts', models.TextField(blank=True, null=True)),
                ('http_urls', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Device')),
            ],
        ),
    ]
