# Generated by Django 2.1.2 on 2018-10-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20181004_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffictest',
            name='https_hosts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
